#:import get_color_from_hex kivy.utils.get_color_from_hex

#:set color get_color_from_hex("#ffffff")
#:set grid_background_color get_color_from_hex("#4467c4")
#:set text_color get_color_from_hex("#4467c4") 
<Chemistry_notes>:
	name:"Chemistry_notes"
	MDFloatLayout:
		size_hint:1,1
		md_bg_color:get_color_from_hex("#4467c4")
		MDIconButton:
			icon:"arrow-left"
			theme_text_color: 'Custom'
			ripple_scale:0
			text_color: get_color_from_hex('#000000')
			pos_hint:{"center_x":.08,"center_y":.95}
			on_release:
				root.manager.goback()
				root.manager.transition.direction = "right"
		MDLabel:
			text:"Chemistry Notes"
			theme_text_color:"Custom"
			text_color:color
			font_name:"Ubuntu/Ubuntu-Bold"
			font_size:"24dp"
			pos_hint:{"center_x":.63,"center_y":.95}	
		MDLabel:
			id:loading
			halign:"center"
			pos_hint:{"center_y":.5}
			font_size:"18dp"
			color:1,1,1,1
			font_name:"Ubuntu/Ubuntu-Bold"
			text:"Loading..." if Mathlist.children == [] else ""
		ScrollView:
			size_hint_y: .9
			do_scroll_y:True
			MDGridLayout:
				cols:1
				size_hint:1,None
				pos_hint:{"top":.9}
				height:self.minimum_height
				spacing:30
				padding:20
				MDList:
					id:Mathlist
					radius:[30]
					spacing:15			
					md_bg_color:get_color_from_hex("#ffffff")
					
		